export const CompanyArray = [
  {
    id: '834-86-02026',
    name: '(주)에이림',
    subName: 'Alim',
    folderName: 'alim',
    startDate: '2022-05-30',
    lastDay: '2022-09-14',
    position: '개발부/사원',
    desc: '포장업계 MES/ERP 프로그램 개발/납품',
    summary: [
      'ERP 프로그램 유지/보수',
      '경영관리, 구매관리, 영업관리 등 이미 개발되어있는 화면 기능 개선 및 사용자들의 사용감 개선',
      '외주업체와 진행중인 발주, 재고, 생산계획 등 외주관련 파트 개발',
      '사용자들을 늘리기 위한 식단관리 화면 개발',
    ],
  },
  {
    id: '250-81-02543',
    name: '(주)알파벳에이',
    subName: 'alphabetA',
    folderName: 'ffeed',
    startDate: '2022-11-07',
    lastDay: '2023-04-27',
    position: '프론트엔드',
    desc: 'ffeed | 브랜드 가구 세컨핸드 커뮤니티 플랫폼',
    summary: [
      '낙후된 브랜드 가구 시장의 인프라를 개선',
      '개발팀과의 협업, 프로젝트 리팩토링',
      'google search console, Analytics 를 활용한 SEO, 유저들의 니즈 파악 및 개선',
    ],
  },
  {
    id: '840-81-03234',
    name: '(주)러너스',
    subName: 'Runners',
    folderName: 'runners',
    startDate: '2023-10-04',
    lastDay: '2024-04-30',
    position: '프론트엔드',
    desc: '센스 | 라이프스타일 혁신을 선두하는 AI 취향 분석 플랫폼',
    summary: ['여자친구를 위한 센스있는 선물 준비하기'],
  },
  {
    id: 'weavrcare',
    name: '(주)위버케어',
    subName: 'Weavrcare',
    folderName: 'weavrcare',
    startDate: '2024-05-01',
    lastDay: '재직중',
    position: '프론트엔드',
    desc: '닥터팔레트 | 클라우드 EMR & 헬스케어 SaaS 플랫폼',
    summary: [
      'React 19, Rspack, Module Federation 기반의 마이크로 프론트엔드 아키텍처 운영',
      '50개 이상의 기능 패키지로 구성된 대규모 모노레포(Turbo) 환경 개발 경험',
      'Jotai, Tailwind CSS 4 등 최신 기술 스택 활용 및 디자인 시스템(Palette Design System) 고도화',
      '병원 진료, 청구, 상담 등 복잡한 도메인 로직을 마이크로서비스(gRPC)와 연동하여 안정적으로 구현',
    ],
  },
  {
    id: 'last-career',
    name: '더 많은 커리어가 추가 될 예정입니다 :)',
    subName: '',
    folderName: '',
    startDate: '',
    lastDay: '',
    position: '',
    desc: '',
    summary: [],
  },
]
