export const CompanyArray = [
  {
    id: '834-86-02026',
    name: '(주)에이림',
    subName: 'Alim',
    folderName: 'alim',
    startDate: '2022-05',
    lastDay: '2022-09',
    position: '개발부/사원',
    desc: '포장업계 MES/ERP 프로그램 개발/납품',
    summary: [
      'ERP 프로그램 유지/보수',
      '경영관리, 구매관리, 영업관리 등 이미 개발되어있는 화면 기능 개선 및 사용자들의 사용감 개선',
      '외주업체와 진행중인 발주, 재고, 생산계획 등 외주관련 파트 개발',
      '사용자들을 늘리기 위한 식단관리 화면 개발',
    ],
  },
  {
    id: '250-81-02543',
    name: '(주)알파벳에이',
    subName: 'alphabetA',
    folderName: 'ffeed',
    startDate: '2022-11',
    lastDay: '2023-05',
    position: '프론트엔드',
    desc: 'ffeed | 브랜드 가구 세컨핸드 커뮤니티 플랫폼',
    summary: [
      '낙후된 브랜드 가구 시장의 인프라를 개선',
      '개발팀과의 협업, 프로젝트 리팩토링',
      'google search console, Analytics 를 활용한 SEO, 유저들의 니즈 파악 및 개선',
    ],
  },
  {
    id: '840-81-03234',
    name: '(주)러너스',
    subName: 'Runners',
    folderName: 'runners',
    startDate: '2023-10',
    lastDay: '2024-12',
    position: '프론트엔드',
    desc: '센스 | 라이프스타일 혁신을 선두하는 AI 취향 분석 플랫폼',
    summary: ['여자친구를 위한 센스있는 선물 준비하기'],
  },
  {
    id: 'weavrcare',
    name: '(주)위버케어',
    subName: 'Weavrcare',
    folderName: 'weavrcare',
    startDate: '2025-01',
    lastDay: '2026-04',
    position: '프론트엔드',
    desc: '닥터팔레트 | 클라우드 EMR & 헬스케어 SaaS 플랫폼',
    summary: [
      '네이버, 여신티켓 등 외부 플랫폼 양방향 예약 연동 FE 전담으로 의원 평균 매출(ARPU) 37% 성장 기여',
      'rspack, Module Federation 기반 MFE 초기 로딩 성능 개선 (Lighthouse TBT 3,560ms → 100~350ms, 10배 개선)',
      'Context API → Jotai 상태관리 전환으로 캘린더 렌더링 성능 최적화',
      'Trunk-Based Development, Feature Flag 활용한 배포 안정성 강화 및 A/B 테스트',
      'Flutter(Dart) 기반 벡터 캔버스 WASM 산출물을 React 앱에 동적으로 로드하는 래퍼 컴포넌트 아키텍처 설계',
      'Antigravity Rules/Workflows/Skills 활용한 에이전트 우선 작업 표준화 및 멀티 에이전트(Gemini, Codex, Claude) 문서 관리',
    ],
  },
  {
    id: 'doctornow',
    name: '(주)닥터나우',
    subName: 'Doctornow',
    folderName: 'doctornow',
    startDate: '2026-04',
    lastDay: '재직중',
    position: '프론트엔드',
    desc: 'MAU 800만 비대면 진료 1위 플랫폼의 웹/앱 개발',
    summary: [
      '고도화된 서비스 안정성을 토대로 프로젝트 정리 및 새로운 방향 제시',
      'React, Next.js, React Native 기반 웹/앱 동시 개발',
    ],
  },
  // {
  //   id: 'last-career',
  //   name: '더 많은 커리어가 추가 될 예정입니다 :)',
  //   subName: '',
  //   folderName: '',
  //   startDate: '',
  //   lastDay: '',
  //   position: '',
  //   desc: '',
  //   summary: [],
  // },
]
