import Next from 'public/svg/Next'
import Aws from 'public/svg/Aws'

export const StacksArray = [
  {
    id: 0,
    name: 'React',
    isPublic: 1,
    desc: '함수형 컴포넌트와 훅, 의존성 주입 등 기본적인 개념을 알고있으며 클린코드와 커스텀 훅에 관심이 많습니다.',
    svg: '/images/React-icon.png',
    svgName: 'React',
    updated: 'Updated now',
    starred: 0,
    level: '60%',
  },
  {
    id: 1,
    name: 'JavaScript',
    isPublic: 1,
    desc: '프론트엔드 개발자에게 가장 중요한 언어라고 생각합니다. 자료구조 및 알고리즘을 자바스크립트로 공부하고 있습니다.',
    svg: '/images/JavaScript_logo_2.png',
    svgName: 'JavaScript',
    updated: 'Updated 29 seconds ago',
    starred: 0,
    level: '60%',
  },
  {
    id: 2,
    name: 'TypeScript',
    isPublic: 1,
    desc: '에이림에서 타입스크립트를 사용하지 않았었기에, 더욱 중점을 두고 공부중입니다.',
    svg: '/images/Typescript_logo_2020.png',
    svgName: 'TypeScript',
    updated: 'Updated 1 minute ago',
    starred: 1,
    level: '40%',
  },
  {
    id: 3,
    name: 'Next.js',
    isPublic: 1,
    desc: '지금의 github.io 페이지는 Next.js 와 emotion 을 사용하여 개발했습니다. 사용경험이 많지않아 더욱 열심히 공부하려 합니다.',
    svg: <Next />,
    svgName: 'Next.js by Vercel',
    updated: 'Updated 20 days ago',
    starred: 1,
    level: '30%',
  },
  {
    id: 4,
    name: 'Aws',
    isPublic: 1,
    desc: 'Spring Boot JPA로 만든 REST-API와 파이썬 flask 서버를 EC2로 배포한 경험이 있고, SPA 배포가 간편한 S3를 사용해보았습니다.',
    svg: <Aws />,
    svgName: 'Amazon Web Service',
    updated: 'Updated 13 days ago',
    starred: 0,
    level: '30%',
  },
  {
    id: 5,
    name: 'Java',
    isPublic: 0,
    desc: '처음 공부한 언어로, 국비교육 당시 가장 중점적으로 다루었습니다. 이 기본기는 타입스크립트를 공부할 때 많은 도움이 되고있어, 한번 배운것은 항상 내 자산이 된다는 것을 느끼게 해주었습니다.',
    svg: '/images/java-4-logo-svgrepo-com.svg',
    svgName: 'Java/Spring',
    updated: 'Updated on 11 Jan',
    starred: 0,
    level: '20%',
  },
]
