import Next from 'public/svg/Next'

export const stacksArray = [
  {
    id: 0,
    name: 'JavaScript',
    isPublic: 1,
    desc: 'Core JavaScript(실행 컨텍스트, 이벤트 루프, 프로토타입)에 대한 깊은 이해를 바탕으로 비동기 병목과 메모리 이슈를 프로파일링하여 해결합니다.\nES Next 문법을 활용해 가독성과 효율성을 갖춘 클린 코드를 지향합니다.',
    svg: '/images/JavaScript_logo_2.png',
    svgName: 'JavaScript',
    updated: 'Updated now',
    starred: 1,
  },
  {
    id: 1,
    name: 'TypeScript',
    isPublic: 1,
    desc: '대규모 프로젝트의 안정성을 책임지는 도구로 활용합니다.\n고도화된 타입 시스템(Generic, Utility Types)을 설계하여 런타임 에러를 사전에 방지하고, DX(개발자 경험)를 고려한 인터페이스를 구축합니다.',
    svg: '/images/Typescript_logo_2020.png',
    svgName: 'TypeScript',
    updated: 'Updated 29 seconds ago',
    starred: 1,
    link: 'https://www.typescriptlang.org/',
  },
  {
    id: 2,
    name: 'React',
    isPublic: 1,
    desc: 'Fiber 아키텍처와 Reconciliation 과정을 이해하며, 렌더링 최적화를 통해 성능을 극대화합니다.\n관심사 분리(SoC) 원칙에 기반한 컴포넌트 설계로 유지보수성과 재사용성을 높인 코드를 작성합니다.',
    svg: '/images/React-icon.png',
    svgName: 'React',
    updated: 'Updated 1 minute ago',
    starred: 1,
    link: 'https://legacy.reactjs.org/',
  },
  {
    id: 3,
    name: 'Next.js',
    isPublic: 1,
    desc: 'Page Router(12v) 실무 경험으로 시작해, App Router 가 출시되고 주도적으로 마이그레이션을 담당했습니다.\n발생하는 각종 이슈를 트러블슈팅하며 구조적 한계와 장단점을 명확히 파악하고 있습니다.',
    svg: <Next />,
    svgName: 'Next.js by Vercel',
    updated: 'Updated 3 hours ago',
    starred: 1,
    link: 'https://nextjs.org/',
  },
  {
    id: 4,
    name: 'Solid.js',
    isPublic: 1,
    desc: 'React와 다른 반응형(Reactive) 프로그래밍 모델의 원리를 이해하고 있습니다.\n가벼운 번들 사이즈와 빠른 렌더링이 필요한 프로젝트에서 Solid.js를 채택하는 등 저에겐 친숙한 프레임워크 입니다.',
    svg: '/images/solid.ico',
    svgName: 'Solid.js',
    updated: 'Updated 2 hours ago',
    starred: 0,
    link: 'https://www.solidjs.com/',
  },
  {
    id: 6,
    name: 'Java',
    isPublic: 0,
    desc: '컴퓨터 공학 및 객체지향 프로그래밍(OOP)의 탄탄한 기반이 된 언어입니다.\n이러한 백엔드/CS 지식을 바탕으로 프론트엔드-백엔드 간의 원활한 커뮤니케이션과 전체 시스템 아키텍처를 이해하는 데 활용합니다.',
    svg: '/images/java-4-logo-svgrepo-com.svg',
    svgName: 'Java/Spring',
    updated: 'Updated on 11 Jan',
    starred: 0,
  },
]
