import Next from 'public/svg/Next'

export const stacksArray = [
  {
    id: 0,
    name: 'JavaScript',
    isPublic: 1,
    desc: '스코프, 실행 컨텍스트, 콜스택, 이벤트 루프의 개념에 대해 알고,\n메모리 누수와 비동기 타이밍 이슈를 추적하고 해결할 수 있습니다.',
    svg: '/images/JavaScript_logo_2.png',
    svgName: 'JavaScript',
    updated: 'Updated now',
    starred: 1,
  },
  {
    id: 1,
    name: 'TypeScript',
    isPublic: 1,
    desc: '협업의 기본이자, 프로덕트의 안정성을 끌어올리는 도구입니다.\n타입 추론을 적극 활용하고 런타임 에러를 원천 차단하는 견고한 타입 시스템을 설계합니다.',
    svg: '/images/Typescript_logo_2020.png',
    svgName: 'TypeScript',
    updated: 'Updated 29 seconds ago',
    starred: 1,
    link: 'https://www.typescriptlang.org/',
  },
  {
    id: 2,
    name: 'React',
    isPublic: 1,
    desc: 'React의 Fiber 아키텍처 원리에 대한 이해를 바탕으로, 불필요한 렌더링을 제어하고 최적화합니다.\n18 버전의 동시성 렌더링 훅을 활용해 끊김 없는 사용자 경험을 설계합니다.',
    svg: '/images/React-icon.png',
    svgName: 'React',
    updated: 'Updated 1 minute ago',
    starred: 1,
    link: 'https://legacy.reactjs.org/',
  },
  {
    id: 3,
    name: 'Next.js',
    isPublic: 1,
    desc: '현 근무지인 위버케어에서는 사용하고 있지 않지만 Page Router 사용 경험이 있으며,\nApp Router로 실무 레벨과 다양한 사이드 프로젝트를 구현해 보았습니다.',
    svg: <Next />,
    svgName: 'Next.js by Vercel',
    updated: 'Updated 3 hours ago',
    starred: 1,
    link: 'https://nextjs.org/',
  },
  {
    id: 4,
    name: 'Solid.js',
    isPublic: 1,
    desc: '반응형 프레임워크를 익히기 좋은 강력한 프레임워크라고 생각합니다. 사용해보니 리액트와 작동방식이 꽤 달라 애먹었던 적도 많았지만, 사이드 프로젝트를 만들때 Solid.js를 사용하여 즐겁게 공부해보았습니다.',
    svg: '/images/solid.ico',
    svgName: 'Solid.js',
    updated: 'Updated 2 hours ago',
    starred: 0,
    link: 'https://www.solidjs.com/',
  },
  {
    id: 6,
    name: 'Java',
    isPublic: 0,
    desc: '개발 첫 공부 언어로, 국비교육 당시 가장 중점적으로 다루었습니다. 이 기본기는 타입스크립트를 공부할 때 많은 도움이 되고있어, 한번 배운것은 항상 내 자산이 된다는 것을 느끼게 해주었습니다.',
    svg: '/images/java-4-logo-svgrepo-com.svg',
    svgName: 'Java/Spring',
    updated: 'Updated on 11 Jan',
    starred: 0,
  },
]
