export const Stacks = [
  {
    id: 0,
    name: 'React',
    isPublic: 1,
    desc: '함수형 컴포넌트와 훅, 의존성 주입 등 기본적인 개념을 알고있으며 클린코드와 커스텀 훅에 관심이 많습니다.',
    svg: '',
    level: '80%',
  },
  {
    id: 1,
    name: 'JavaScript',
    isPublic: 1,
    desc: '프론트엔드 개발자에게 가장 중요한 언어라고 생각합니다. 자료구조 및 알고리즘을 자바스크립트로 공부하고 있습니다.',
    svg: '',
    level: '60%',
  },
  {
    id: 2,
    name: 'TypeScript',
    isPublic: 1,
    desc: '에이림에서 타입스크립트를 사용하지 않았었기에, 더욱 중점을 두고 공부중입니다.',
    svg: '',
    level: '40%',
  },
  {
    id: 3,
    name: 'AWS',
    isPublic: 1,
    desc: '파이썬 flask 서버와 Spring Boot JPA로 만든 REST-API 를 EC2로 배포한 경험이 있고, SPA 배포가 간편한 S3를 사용중입니다.',
    svg: '',
    level: '20%',
  },
  {
    id: 4,
    name: 'Java',
    isPublic: 0,
    desc: '처음 공부한 언어로, 국비교육 당시 가장 중점적으로 다루었습니다. 이 기본기는 타입스크립트를 공부할 때 많은 도움이 되고있어, 한번 배운것은 항상 내 자산이 된다는 것을 느끼게 해주었습니다.',
    svg: '',
    level: '20%',
  },
]
