import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'

const About: NextPage = () => {
  return (
    <div style={{ height: '100vh' }} id="About">
      {/*<Head>*/}
      {/*  <title>About Me</title>*/}
      {/*  <meta name="description" content="Generated by create next app" />*/}
      {/*  <link rel="icon" href="/favicon.ico" />*/}
      {/*</Head>*/}

      <br />

      <Link href="/">
        <button>안녕</button>
      </Link>
    </div>
  )
}

export default About
