import type { NextPage } from 'next'
import Head from 'next/head'
import styled from '@emotion/styled'
import LeftBar from '@components/LeftBar'
import RightContent from '@components/RightContent'
import ScrollProgress from '@components/ScrollProgressBar'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>프론트엔드 개발자 이한울</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ScrollProgress />

      <Container>
        <LeftBar />
        <RightContent />
      </Container>
    </div>
  )
}

const Container = styled.div`
  padding: 0 1rem;
  max-width: 90vw;
  display: flex;
  flex: 1;
  //justify-content: center;
  //align-items: center;
  margin: 0 auto;
`

export default Home
