import ClientRootContext from '@/context/client-root-context';
import { PropsWithChildren } from 'react';

import '@/styles/global-styles.css';
import '@/styles/tailwind.css';

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

/**
 * 모든 페이지에 적용되는 RootLayout 이므로 레이아웃(스타일) 컴포넌트는 적용을 지양합니다.
 */
export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html className="dark">
      <body>
        <ClientRootContext>
          <div id="portal" />
          <div id="modal" />
          {children}
        </ClientRootContext>
      </body>
    </html>
  );
}
